version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nl.jqno.equalsverifier:equalsverifier
    versions:
    - 3.5.2
    - 3.5.3
    - 3.5.4
    - 3.5.5
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
